### ISSUE TITLE
Set Whitelist in options

### ISSUE THREAD

**Issue by ecirish** [lwhiteley/feathers-lowdb#11]
Is there a way I can pass a whitelist of query params to the service?

**Comment by lwhiteley** [comment]
currently not accounted for but a PR can be submitted to take care of this. I have little time to do it until the next few days. so  if you want to submit a PR, ill gladly review it

**Comment by ecirish** [comment]
I ended up just setting it on the service after creation, like so:

```
const service = app.service('service')

service.options.whitelist = app.get('whitelist')
```

Seems like a simple enough way to do it. Probably not necessary to bake it into this codebase.

**Comment by lwhiteley** [comment]
ah thats great to know!
