### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by ecirish** [lwhiteley/feathers-lowdb#12]
LowDB lists support for YAML.  Are there any plans to add YAML support for this adapter?

**Comment by lwhiteley** [comment]
ill look at it over the weekend, thanks for pointing it out

**Comment by lwhiteley** [comment]
Based on the lowdb docs you could actually just add yaml support using the adapter.

```js
const adapter = new FileSync('array.yaml', {
  defaultValue: [],
  serialize: (array) => toYamlString(array),
  deserialize: (string) => fromYamlString(string)
})
```

This library doesnt restrict you to which adapter you want to use..

I havent tested yet but presumably you could do

```js
const low = require('lowdb');
const FileSync = require('lowdb/adapters/FileSync');
const service = require('feathers-lowdb');

const adapter = new FileSync('./data/messages.yaml', {
  defaultValue: [],
  serialize: (array) => toYamlString(array),
  deserialize: (string) => fromYamlString(string)
});
// Create a LowDB instance
const Model = low(adapter);

app.use('/messages', service({ Model }));
app.use('/messages', service({ Model, id, events, paginate }));
```

you can use https://www.npmjs.com/package/yaml to serialize and deserialize the yaml

**Comment by ecirish** [comment]
@lwhiteley That works! Thanks!
