### ISSUE TITLE
lowdb v3 has no default function in model

### ISSUE THREAD

**Issue by FossPrime** [lwhiteley/feathers-lowdb#34]
### Steps to reproduce

Using lowdb v3 with either sync or async modes will result in a `default is not a function` error.

Reproduction
https://stackblitz.com/edit/feathersjs-bypass-app-hooks?file=src/services/users.service.js

---

Update: V3 is a major overhaul of LowDB... for us these are some of the major issues:
- lodash not included by default
- chaining syntax is a little different.
- Performance is now more in our control

I tried my hand at a V3 update... it didn't go great. Only 54 tests passing and 122 failing. I'm missing something fundamental.
https://github.com/FossPrime/feathers-lowdb/tree/v3

**Comment by lwhiteley** [comment]
the lib is really lowdb version agnostic so maybe documentation show how to use it additionally since v3 would resolve this.

**Comment by FossPrime** [comment]
Dove version with YAML as default... https://github.com/FossPrime/feathers-lowdb-yaml

Just got it fully working so... API is a bit rough, no JSON support, no custom model support, and due to LowDB@3... it's ESM only

It's based on @feathersjs/memory  havent gotten to renaming on publishing to NPM yet...

Are you open to a major update and sharing npm access? otherwise I'll publish to https://www.npmjs.com/package/feathers-yaml
